### ISSUE TITLE
Storybook no longer builds, works.

### ISSUE THREAD

**Issue by aembler** [concretecms/bedrock#183]
Storybook is currently broken in this repository.

The issues are probably related to a number of different things.

1. The structure of the SCSS files has changed a bit since we first implemented it. You can see this if you compare the Dashboard main.scss in the concrete5 repo with the Storybook main.scss. 
2. I'm getting a ton of JavaScript errors (which shouldn't be the case, I don't think - we haven't significantly updated the JS dependencies for things like Vue since implementing Storybook)
3. I think there are some errors that @mlocati believes are a result of us not using the latest version of Webpack (which would require us to update to Laravel Mix 6).

@KorvinSzanto if you can fix 2 and 3 I can look into fixing 1, since I have a bit of experience with that one. In the meantime, I have disabled the Storybook workflow because it will never complete until this is fixed.

**Comment by puka-tchou** [comment]
Hello, any updates on this issue? Have you had the time to try to solve it? If not, I might give it a go.

**Comment by aembler** [comment]
We haven't. @KorvinSzanto might be looking into it soon or he might be looking for alternatives to this functionality altogether.

**Comment by KorvinSzanto** [comment]
Storybook is back in action in the `feature/vue3` branch
