### ISSUE TITLE
File Chooser: Filter by extension doesn't work as expected written in the phpdoc

### ISSUE THREAD

**Issue by hissy** [concretecms/bedrock#292]
File chooser is expected to be filterable by file extension, but it doesn't work with the example code in the phpdoc.

https://github.com/concretecms/concretecms/blob/9.2.0/concrete/src/Application/Service/FileManager.php#L14-L53

However, it works when you remove dots like this: `'extension' => ['png', 'jpg']`

IMO, we should fix the file chooser to work with the example code. Otherwise, we can update the phpdoc if we can ignore backward compatibility.

Related PR: #193

**Comment by mlocati** [comment]
I'm using it in a project of mine that uses Vue directly, and it works as expected:

```html
<concrete-file-picker
    results-form-factor="list"
    v-bind:enable-pagination="true"
    v-bind:enable-sort="true"
    v-bind:filters="[{filter: 'extension', extensions: ['pdf', 'zip']}]"
    v-bind:multiple-selection="false"
    route-path="/ccm/system/file/chooser/get_folder_files/<?= $folderID ?>"
></concrete-file-picker>
```

**Comment by hissy** [comment]
@mlocati Yeah, it works with `['pdf', 'zip']` but doesn't with `['.pdf', '.zip']` .
Please check the phpdoc of the FileManager class.

**Comment by mlocati** [comment]
So I guess we only need to fix the phpdoc

**Comment by hissy** [comment]
@mlocati 
Oh, you are the one who wrote this phpdoc 5 years ago! So you meant the doc is wrong, right?
https://github.com/concretecms/concretecms/commit/8c5e2c59ec9f00aadc04dcdfe7f434a4de06d6b7

**Comment by mlocati** [comment]
If the version with dots doesn't work, and the version without dots works, I guess that I wrote a wrong phodoc, or that something changed in the last 5 years.

**Comment by aembler** [comment]
Yeah I suspect mlocati is right - I think the original implementation (with the dots) was documented correctly, but that's kind of a silly way to do it. The extension is the extension - it shouldn't need the dot in front of it in the filter, which is why we changed it when it came time to implement the component. Let's fixed the phpdoc.
